---
- name: install utilities and dependencies RedHat
  yum:
    name: "{{ item }}"
    update_cache: yes
  when: ansible_os_family == "RedHat"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: true

- name: install yum repo for Docker
  yum_repository:
    name: Docker Repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_os_family == "RedHat"
  become: true

- name: Install Docker CE
  yum:
    name: docker-ce
    update_cache: yes
  become: true
